/**
 * Build static site for GitHub Pages into docs/
 */
import { cpSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = resolve(root, 'public');
const docsDir = resolve(root, 'docs');

if (existsSync(docsDir)) {
  rmSync(docsDir, { recursive: true, force: true });
}
mkdirSync(docsDir, { recursive: true });

cpSync(publicDir, docsDir, { recursive: true });

// PWA manifest alias (index.html references manifest.webmanifest)
const manifestSrc = resolve(docsDir, 'manifest.json');
if (existsSync(manifestSrc)) {
  cpSync(manifestSrc, resolve(docsDir, 'manifest.webmanifest'));
}

writeFileSync(resolve(docsDir, '.nojekyll'), '');
writeFileSync(
  resolve(docsDir, 'README-GITHUB-PAGES.txt'),
  'This folder is generated by scripts/build-pages.mjs for GitHub Pages. Do not edit manually.\n',
);

console.log('GitHub Pages build complete → docs/');
